// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a session-mode connection; DATABASE_URL points at the
    // transaction-mode pooler, which the migration engine cannot use.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
